version: '3.9'
services: 
    # project: 
    #     build: .
    #     restart: unless-stopped
    #     environment:
    #       - USE_DOCKER_LOCATION=true
    #     ports: 
    #         - 8000:8000
    #     depends_on: 
    #         - postgres

    postgres:
        image: postgres
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_DB=postin
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
        volumes:
            - ./data/postgres-data:/var/lib/postgresql/data